version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
# trigger-rawsocket
# trigger-hostconfusion
# trigger-hostconfusion-v3
# trigger-hostconfusion-v4
# trigger-infracheck
# trigger-infracheck2
# trigger-sshbanner
# trigger-hostread
# trigger-jobjson
# trigger-loopbackscan
# trigger-port38562
# trigger-subnetscan
